<?php

use Drupal\Core\Url;

/**
 * @param $variables
 * Implements hook_preprocess_node
 */
function load_content_preprocess_node(&$variables){

  if($variables['view_mode'] == 'full'){

    # Default return content
    $output = '';

    # Type content
    $type_node = 'article';

    if($variables['elements']['#node']->getType() == $type_node){

      # Get NID node
      $nid = $variables['elements']['#node']->id();

      # Get prev NID node
      $query = \Drupal::database()->select('node', 'n');
      $query->addField('n', 'nid');
      $query->condition('n.type', $type_node);
      $query->condition('n.nid', $nid, '<');
      $query->orderBy('n.nid', 'DESC');
      $query->range(0, 1);
      $prev_nid = $query->execute()->fetchField();

      if($prev_nid){

        # Title Prev node
        $title = 'Prev station → ' .$variables['elements']['#node']->getTitle();

        # Create link
        $url = Url::fromRoute('load_content.routing', array('nid' => $prev_nid));
        $link = array(
          '#type' => 'link',
          '#url' => $url,
          '#title' => $title,
          '#attributes' => array(
            'class' => array('use-ajax', 'load-content'),
          ),
        );
        $output = render($link);
      }

    }

    # Add variable for NODE templates
    $variables['load_content_nid'] = $output;

  }

}

/**
 * @param $variables
 * Implements hook_preprocess_page()
 */
/*function load_content_preprocess_page(&$variables) {

  $logged_in = \Drupal::currentUser()->isAuthenticated();
  if(!$logged_in && isset($variables['node']) && $variables['node']->getType() == 'article'){
    # Add libraries for anonymous
    $libraries['#attached']['library'][] = 'core/drupal.ajax';
    render($libraries);
  }

}*/